FROM nginx:alpine

RUN apk add --no-cache openssl

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/easytrip.kro.kr/certificate.crt /etc/ssl/certificate.crt
COPY ./nginx/easytrip.kro.kr/ca_bundle.crt /etc/ssl/ca_bundle.crt
COPY ./nginx/easytrip.kro.kr/private.key /etc/ssl/private.key

RUN cat /etc/ssl/certificate.crt /etc/ssl/ca_bundle.crt >> /etc/ssl/merged_certificate.crt

