server:
  port: ${server_port}
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  shutdown: graceful

spring:
    config:
        import: "optional:configserver:"
    application:
        name: "post"
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${issuer-uri}
    cloud:
        function:
            definition: postWrite;postUpdate;postDelete
        stream:
            bindings:
                postWrite-in-0:
                    destination: post-write
                    content-type: application/json
                    group: ${spring.application.name}
                postUpdate-in-0:
                    destination: post-update
                    content-type: application/json
                    group: ${spring.application.name}
                postDelete-in-0:
                    destination: post-delete
                    content-type: application/json
                    group: ${spring.application.name}
                acceptPost-out-0:
                    destination: post-accepted
                    content-type: application/json
    rabbitmq:
        host: ${rabbitmq_host}
        port: ${rabbitmq_port}
        username: ${rabbitmq_username}
        password: ${rabbitmq_password}
        connection-timeout: 5s
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 1000
                    max-interval: 10000
                    multiplier: 2
    data:
        mongodb:
            uri: ${mongodb_uri}
            database: ${mongodb_database}
logging:
  level:
    org.springframework.cloud.stream: DEBUG