spring:
    config:
        import: "optional:configserver:"
    application:
        name: "orchestration"
    cloud:
        stream:
            bindings:
                transactionPost-in-0:
                    destination: post-transaction
                    content-type: application/json
                    group: ${spring.application.name}
                post-out-0:
                    destination: post-write
                    content-type: application/json
                budget-out-0:
                    destination: budget-write
                    content-type: application/json
                plan-out-0:
                    destination: plan-write
                    content-type: application/json
    rabbitmq:
        host: ${rabbitmq_host}
        port: ${rabbitmq_port}
        username: ${rabbitmq_username}
        password: ${rabbitmq_password}
        connection-timeout: 5s
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3
                    initial-interval: 1000
                    max-interval: 10000
                    multiplier: 2
logging:
  level:
    org.springframework.cloud.stream: DEBUG